### ISSUE TITLE
GUI Demo fails when relating services

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#121] opened 2015-07-21 10:46 UTC
The GUI fails to relate services when attempting to build a bundle in the Demo.

It appears there's some javascript schenanigans according to the console output of the browser. 
Google Chrome Version 43.0.2357.134 (64-bit)

![selection_010](https://cloud.githubusercontent.com/assets/246944/8798929/032aef9e-2f74-11e5-88c2-e81b23d397a1.jpg)

**Comment by mitechie** [comment] 2015-07-21 11:00
I'm currently unable to reproduce this. Can you be more specific on the charms involved (I can see their names, but not which user they're ffrom) and which relations you attemped?

I build this (ignore the icon flakiness atm) here:

![selection_011](https://cloud.githubusercontent.com/assets/75915/8799175/3137317a-2f76-11e5-8b6c-6868bbf9d74f.png)

**Comment by mitechie** [comment] 2015-07-21 11:01
Hmm, I'm on charome 42, updating to 43 to see if something is up thee.

**Comment by mitechie** [comment] 2015-07-21 11:06
I've updated my dev channel chrome but still only on 42. Did you get 43 from another source?

**Comment by mitechie** [comment] 2015-07-24 02:35
@chuckbutler closing atm. Please reopen with additional details if you're still seeing this.

**Closed as completed by mitechie** 2015-07-24 02:35 UTC
