### ISSUE TITLE
https://jujucharms.com/docs/stable/getting-started-general/ 404

### ISSUE THREAD

**Issue by brendan-donegan** [canonical/jujucharms.com#283] opened 2016-06-01 10:14 UTC
The above page 404s

**Comment by frankban** [comment] 2016-06-10 12:24
Where is that page linked from?

**Comment by slimjim777** [comment] 2016-06-20 15:42
Go to https://jujucharms.com/

Then clicking the Docs link gives you a 404 (https://jujucharms.com/docs/getting-started/). I'm sure this was working before, but I'm getting a lot of 404s from the docs pages.

**Comment by anthonydillon** [comment] 2016-06-21 07:59
I don't seem to be able to find any links to https://jujucharms.com/docs/stable/getting-started-general/  from the homepage. Also the docs links all go to https://jujucharms.com/docs/stable/getting-started which is the correct docs landing page. 

Are you still able to reproduce this? Nothing is 404'ing for me.

**Comment by slimjim777** [comment] 2016-06-21 13:33
The links were working and then stopped working (404's everywhere) and then worked again. It's possible that it was a service that was being rebooted or updated. It's been fine for me today. The 'getting-started-general' link may have been an old one.

**Comment by anthonydillon** [comment] 2016-06-21 13:37
Thanks for confirming. There must have been a temporary outage due to a release. Closing this issue but please reopen if it occurs again.

**Closed as completed by anthonydillon** 2016-06-21 13:37 UTC
Labels: needs-feedback
