### ISSUE TITLE
missing page https://jujucharms.com/docs/stable/howto-node/

### ISSUE THREAD

**Issue by tyloch** [canonical/jujucharms.com#375] opened 2016-11-16 19:34 UTC
404 for https://jujucharms.com/docs/stable/howto-node/

**Comment by anthonydillon** [comment] 2016-11-17 07:59
Thank you very much for taking the time to report this issue.

Can you please provide the page and link which brought you to the 404 page. This will help us to find and correct any out of date content.

**Comment by tyloch** [comment] 2016-11-17 08:31
It is
https://jujucharms.com/docs/stable/howto-node/

**Comment by tyloch** [comment] 2016-11-17 08:32
It is 
"Sorry, we couldn’t find the page you’re looking for." page i call it 404

**Comment by anthonydillon** [comment] 2016-11-17 08:42
Sorry if I wasn't clear but how did you find yourself on that page. Is
there a link to it somewhere? Or is it bookmarked? Thanks again.

**Comment by bac** [comment] 2016-11-17 13:40
@anthonydillon This may be related to #374

**Comment by bac** [comment] 2016-11-17 13:41
@tyloch Can you confirm you clicked on a link returned from searching and that's what led you to the 404 page?

**Comment by tyloch** [comment] 2016-11-17 14:20
AFAIR I clicked on a link on main doc page

**Comment by tyloch** [comment] 2016-11-17 14:22
I.e. table of content

**Comment by bac** [comment] 2016-11-17 14:27
Thanks @tyloch. I see this is a duplicate of the bug at https://github.com/juju/docs/issues/1534

I'm going to close this one as it is being tracked in the docs project. Thanks for the feedback and for filing the issue. Hopefully we'll get this sorted out soon.

**Closed as completed by bac** 2016-11-17 14:27 UTC
Labels: needs-feedback
