### ISSUE TITLE
Juju command reference docs missing anchors

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#516] opened 2018-01-19 21:19 UTC
The juju command reference docs could really use some anchors so people can link specific commands.

I've created an issue for the docs juju/docs#2365, but was redirected here.

**Comment by anthonydillon** [comment] 2018-01-22 08:00
Thank you @szeestraten-ntnu. This could be an issue for either project depending on the solution. I believe this issue would be resolved by design taking a look at this section of the docs. I have suggested that each command could have its own page too make it easier to search for commands: https://github.com/CanonicalLtd/jujucharms.com/issues/515.

**Comment by pmatulis** [comment] 2019-06-21 13:59
@anthonydillon The larger issue is that heading anchor links are not readily available to users throughout the docs.

**Comment by pmatulis** [comment] 2019-06-21 14:00
*Not sure how I could have unassigned anyone. I don't even have the permission to do so.*

**Comment by anthonydillon** [comment] 2019-08-08 09:06
@hatched could you choose this issue please.

**Closed as completed** 2019-08-08 17:07 UTC
Labels: design
