### ISSUE TITLE
Charm info page sticky header doesn't show icon or charm name

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#445] opened 2017-03-21 18:41 UTC
e.g. https://jujucharms.com/nova-cloud-controller/#configuration shows as https://pageshot.net/b9E1TwHBeZug7tvj/jujucharms.com in both Firefox (v53.0a2) and Chrome on Ubuntu 16.04

**Comment by frankban** [comment] 2017-03-21 20:49
This seems to be a duplicate of https://github.com/CanonicalLtd/jujucharms.com/issues/418

**Closed as completed by frankban** 2017-03-21 20:49 UTC
Labels: duplicate
