### ISSUE TITLE
bundle redirect is wrong/broken

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/jujucharms.com#485] opened 2017-09-11 02:07 UTC
Bundle url redirect doesn't include charm rev when not logged in.
<img width="1418" alt="screen shot 2017-09-10 at 7 07 38 pm" src="https://user-images.githubusercontent.com/5590546/30255860-59de164a-965b-11e7-9a46-b2eb1cc0b5a4.png">

To reproduce:
1) Go to user page on jujucharms.com - https://jujucharms.com/u/jamesbeedy
2) Click the "django" bundle
3) click the "View" button

You should be redirected to https://jujucharms.com/u/jamesbeedy/django/ not the correct url which includes the rev, https://jujucharms.com/u/jamesbeedy/django/3.

**Comment by mitechie** [comment] 2017-09-11 11:22
@jamesbeedy is this bundle published into the stable channel? This sounds like it's behaving like an unpublished revision.

**Comment by jamesbeedy** [comment] 2017-09-11 21:24
@mitechie its published to the 'beta' channel ... does it have to be published to stable for the rev to get appended to the url when you click the "View" button?

**Comment by mitechie** [comment] 2017-09-11 21:30
Yes, until it's a stable release the store won't give anyone it by default.
They'll have to specify the revision specifically or deploy with a
--channel option to get it to just go and deploy. We don't want users to
accidentally deploy to production something that's not ready.

**Comment by mitechie** [comment] 2017-09-11 21:31
Closing as it's working as intended at the moment. Please let me know if you have any issue after it hits stable.

**Closed as completed by mitechie** 2017-09-11 21:31 UTC
