### ISSUE TITLE
the card sharing code isn't correct 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#457] opened 2017-04-28 13:02 UTC
Selecting and copying the text for sharing a card I get:
https://jujucharms.com/u/spiculecharms/gitlab-ssl

    <script src="https://assets.ubuntu.com/v1/juju-cards-v1.5.0.js"><\/script>\n<div class="juju-card" data-id="~spiculecharms/bundle/gitlab-ssl-4"></div>

The escaped closing block on the script tag and the \n show up for the end user and mess up embedding.

**Comment by anthonydillon** [comment] 2017-05-01 12:56
I don't see the formatting in the output. Here is the output from the about
when copy and pasted. Using Chrome.

<script src="https://assets.ubuntu.com/v1/juju-cards-v1.5.0.js"></script>
<div class="juju-card" data-id="~spiculecharms/bundle/gitlab-ssl-4"></div>

Which browser and version are you seeing the `/n`? Do you also see it on
the cards page https://jujucharms.com/community/cards?

Thanks,
Ant.

**Comment by mitechie** [comment] 2017-05-01 13:00
I do not see it on the cards output. In looking it's specific to the GUI served pages. 

If you go to jujucharms.com/ceph you'll note the code is ok. Now login and revisit the page and get GUI served content and you have the bad content.

**Comment by anthonydillon** [comment] 2017-05-01 13:50
Oh I see, then it's an issue on Juju GUI, not the storefront. Thanks for reporting.

**Comment by Lukewh** [comment] 2017-06-09 13:35
@mitechie do you still see this problem? I can't reproduce

**Comment by frankban** [comment] 2018-07-30 10:18
This is fixed in the GUI.

**Closed as completed by frankban** 2018-07-30 10:18 UTC
Labels: bug
