### ISSUE TITLE
Not able to access private charm files

### ISSUE THREAD

**Issue by simonklb** [canonical/jujucharms.com#442] opened 2017-03-17 21:35 UTC
I'm able to access this file:
https://api.jujucharms.com/charmstore/v5/~elastisys/charmscaler/archive/tox.ini
But I'm not able to access this:
https://api.jujucharms.com/charmstore/v5/~simonklb/charmscaler/archive/tox.ini

It might be related to the ACL since the first charm has `read=everyone` while the second one is only accessible by my own user.

**Comment by jrwren** [comment] 2017-03-20 16:26
You are exactly right. This is by design.

If you want to give access, then grant read=everyone on the charm which currently lacks everyone access.

**Comment by simonklb** [comment] 2017-03-20 17:27
Yes, but I have access to my own charm, right? So I should be able to access it even though the charm does not have been granted read=everyone.

**Comment by simonklb** [comment] 2017-03-20 17:29
Just to clarify - this is still the case even though I'm signed in.

**Comment by jrwren** [comment] 2017-03-21 16:36
I see. Yes, you should still be able to access it, using the web browser in which you are logged in. I assumed that you were using something other than a browser to try to access these files.

Are you saying this is not true? Which browser are you using?

I tried to reproduce this behavior but I cannot. I am able to read such files using my browser.

Using an unauthenticated client such as curl, I cannot read the file. This is by design.

**Comment by simonklb** [comment] 2017-03-21 20:03
I'm authenticated and when I go to https://api.jujucharms.com/charmstore/v5/~simonklb/charmscaler/archive/tox.ini I see:
`{"Message":"no matching charm or bundle for cs:~simonklb/charmscaler","Code":"not found"}`

I'm using Chrome

**Comment by jamesbeedy** [comment] 2017-03-21 20:05
I can verify I am experiencing this same behavior.

**Comment by jrwren** [comment] 2017-03-21 20:47
@jamesbeedy on what charm are you experiencing this behavior? Given we are discussing not-public charms, it is very difficult for me to debug, given that I should see a "no matching charm or bundle..." message, because I do not have permission to said charm.

Perhaps, to debug this, you could give me, "evarlast" read access to a charm under test?

While we are debugging, I've granted jamesbeedy and simonklb read access to a non-public charm under my name, cs:~evarlast/trusty/test-charm-1

Still, I do not get "no matching charm" when I use curl or private browsing/incognito mode. I do get an auth request. This makes me think your username is not simonklb or that the charm name is not "cs:~simonklb/charmscaler"  What does charm list show has the charm name?

**Comment by simonklb** [comment] 2017-03-21 21:31
I'm accessing the tox.ini file through the webpage (https://jujucharms.com/u/simonklb/charmscaler/8). Both the username and charm name is definately correct.

**Comment by jamesbeedy** [comment] 2017-03-21 23:30
@jrwren I don't see your charm at all.

<img width="1427" alt="screen shot 2017-03-21 at 4 28 02 pm" src="https://cloud.githubusercontent.com/assets/5590546/24175380/1ccda8aa-0e53-11e7-9626-c40edb4f349b.png">

@jrwren I've granted you read on a beanstalkd charm under my team (creativedrive) private namespace via `charm grant cs:~creativedrive/beanstalkd-2 everlast --acl read`. This charm exhibits the behavior described above.

**Comment by jamesbeedy** [comment] 2017-03-21 23:46
@simonklb @jrwren Found it! The charm rev isn't being appended to the charm name in the url.

When I click on the Makefile in the beanstalkd charm, it sends me here (notice no charm rev in the url) https://api.jujucharms.com/charmstore/v5/~creativedrive/beanstalkd/archive/Makefile

<img width="1275" alt="screen shot 2017-03-21 at 4 47 09 pm" src="https://cloud.githubusercontent.com/assets/5590546/24175850/cfad1c6a-0e55-11e7-9053-528b554f6509.png">


But if I append the rev https://api.jujucharms.com/charmstore/v5/~creativedrive/beanstalkd-2/archive/Makefile

<img width="1187" alt="screen shot 2017-03-21 at 4 48 37 pm" src="https://cloud.githubusercontent.com/assets/5590546/24175874/f2dbfd8c-0e55-11e7-8030-9c432195310f.png">

**Comment by jamesbeedy** [comment] 2017-03-21 23:49
@simonklb will you reopen this pls?

**Comment by jrwren** [comment] 2017-03-22 03:04
I'll re-open it.

FYI: We have a fix-pending release for the URL used in that files section of the GUI

**Comment by simonklb** [comment] 2017-03-22 11:27
@jamesbeedy Nice catch!

**Comment by frankban** [comment] 2017-03-22 11:34
Exactly, this should have been fixed at https://github.com/juju/juju-gui/pull/2641
It will be part of next production deployment.

**Comment by frankban** [comment] 2017-03-22 12:37
This is now deployed on production. Closing this bug, for any remaining issues feel free to reopen it.
Thanks for your feedback!

**Closed as completed by frankban** 2017-03-22 12:37 UTC
Labels: bug, fix-committed
