### ISSUE TITLE
Searching causes 502 error

### ISSUE THREAD

**Issue by nskaggs** [canonical/jujucharms.com#24] opened 2014-12-09 14:07 UTC
Performing a search using the searchbox prominently featured on many jujucharms.com pages results in a bad gateway error. The resulting URL is https://jujucharms.com/q/*, for example

https://jujucharms.com/q/mysql

**Comment by urosj** [comment] 2014-12-09 14:20
Those are fixed with the new release: 

https://staging.jujucharms.com/q/mysql

Not sure if /q/\* behaves as expected with: https://staging.jujucharms.com/q/*

**Comment by nskaggs** [comment] 2014-12-09 14:32
Staging looks correct. I may have mislead you with the *, I was just trying to say it failed with any search string. Thanks!

**Comment by mitechie** [comment] 2014-12-09 14:38
closing this, the issue is the 502 gateware failure due to ES being down.

**Closed as completed by mitechie** 2014-12-09 14:38 UTC
