### ISSUE TITLE
Bundle names not rendered correctly

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#405] opened 2017-02-24 21:23 UTC
When not logged into jujucharms.com bundle names don't seem to be rending correctly.  I see bundle-name #version 

![resourcemanager](https://cloud.githubusercontent.com/assets/1707853/23321403/ae4bf584-fadf-11e6-8067-ccf36c0f24e5.png)
![cwr-ci](https://cloud.githubusercontent.com/assets/1707853/23321404/ae4d2472-fadf-11e6-813a-da000592c933.png)
![screenshot from 2017-02-24 14-19-55](https://cloud.githubusercontent.com/assets/1707853/23321402/ae49cce6-fadf-11e6-80c2-e1f58451ee7c.png)

I don't see this when I am logged in to jujucharms.com

![untitled-jujucharms](https://cloud.githubusercontent.com/assets/1707853/23321416/bef6f3de-fadf-11e6-8e4e-b24d96854062.png)

**Comment by frankban** [comment] 2017-03-03 10:54
@Lukewh is this the new intended design for charm/bundle revisions?
Could you please take a look?

**Comment by Lukewh** [comment] 2017-03-03 11:19
@frankban @bac The logged out version is the correct version. The latest GUI (not live yet) should make the GUI consistent. I'll leave this issue open until I've confirmed.

**Comment by Lukewh** [comment] 2017-03-20 15:15
I can confirm this is now consistent in both auth states. Closing issue.

**Closed as completed by Lukewh** 2017-03-20 15:15 UTC
Labels: fix-committed, needs-investigation
