### ISSUE TITLE
https://jujucharms.com/docs/devel/credentials is 404

### ISSUE THREAD

**Issue by nskaggs** [canonical/jujucharms.com#238] opened 2016-03-30 21:41 UTC
https://jujucharms.com/docs/devel/credentials is linked from https://jujucharms.com/docs/devel/getting-started, but does not exist.

**Comment by pmatulis** [comment] 2016-03-31 22:00
Thank you but this is a duplicate of https://github.com/juju/docs/issues/938.
Please close this.

**Comment by bac** [comment] 2016-04-01 15:25
Thanks for the report @nskaggs but as it is a duplicate of the juju/docs issue I'm closing this one.

**Closed as completed by bac** 2016-04-01 15:25 UTC
Labels: duplicate
