### ISSUE TITLE
updated README for ibm-db2 not showing up in the store

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#189] opened 2016-01-05 17:13 UTC
IBM updated the ibm-db2 README.md in late December, but the update is not being reflected in the store:

https://jujucharms.com/u/ibmcharmers/ibm-db2/trusty/

When I click the "view code" link on that page, I correctly see the most recent README.md from trunk:

http://bazaar.launchpad.net/~ibmcharmers/charms/trusty/ibm-db2/trunk/view/head:/README.md

But when I click the "README.md" link on the above page, I see an older version:

https://api.jujucharms.com/charmstore/v4/~ibmcharmers/trusty/ibm-db2/archive/README.md

You can compare these versions by searching for the _ibm-db2 host_ string.  Outdated README will show:

```
juju set ibm-db2 host="1.2.3.4"
```

New README should show:

```
juju set ibm-db2 host="x.x.x.x"
```

Can someone help figure out why the store is not picking up the latest README from trunk?  Thanks!

**Comment by lazypower** [comment] 2016-01-11 16:44
This appears to be part of a larger ingestion issue. I'm pointing users @ this bug to chime in and add their charm package if they wish for tracking of their ingestion job

**Comment by jcsackett** [comment] 2016-01-11 17:17
Ingestion is down, presently. We're currently investigating the issue and we'll update here as its resolved.

**Comment by jcsackett** [comment] 2016-01-11 20:29
We restarted the ingestion process, and https://jujucharms.com/u/ibmcharmers/ibm-db2/trusty/ has updated. You can see the updated readme both at the jujucharms link or at https://api.jujucharms.com/charmstore/v4/%7Eibmcharmers/trusty/ibm-db2/archive/README.md

We're still investigating the cause of this outage and so we're leaving this bug open, but for now it seems charms are updating again. Thanks for bringing this to our attention!

**Comment by Yrrsinn** [comment] 2016-01-12 17:14
@jaycee as mentioned in https://lists.ubuntu.com/archives/juju/2016-January/006311.html
"Charms are showing up in the named store now
https://jujucharms.com/u/3-bruno/, but every revision is presented as a
single submitted charm. Not sure if this is the intended behavior or an
error?"

**Comment by jcsackett** [comment] 2016-01-14 14:00
@Yrrsinn that's actually a separate issue--it has been fixed in the codebase but that fix hasn't been rolled out to production yet. We're aiming for the fix to rollout next week.

**Comment by matthewdupre** [comment] 2016-01-14 17:28
I've also seen this, so subscribing to this issue.

I pushed a bundle to Launchpad over 3 hours ago, but there's no sign of it in the charm store: https://code.launchpad.net/~project-calico/charms/bundles/openstack-calico/bundle.

**Comment by bac** [comment] 2016-01-15 13:06
Hi @matthewdupre I had a look at your openstack-calico bundle and found that there are problems with the bundle.

From within your branch, if you should run `juju bundle proof`.  This plugin is provided by the 'charm-tools' package.

Unfortunately, your bundle is missing the 'charm' option for two services and that causes the proof tool to crash. I have created https://github.com/juju/charm-tools/issues/89 to get that issue solved.

After adding the missing 'charm' options your bundle still does not pass the proof step. 

Charms and bundles that do not pass 'proof' are not ingested. Unfortunately we have no feedback mechanism to alert the author when this happens. Authors are expected to run `juju charm proof` or `juju bundle proof` as a preliminary step. You can read about the tools at
https://jujucharms.com/docs/stable/authors-charm-writing
and
https://jujucharms.com/docs/stable/tools-charm-tools

I realize this process is less than ideal and we'll think of ways to provide feedback.

Feel free to contact us on Freenode in the #juju-gui channel if you have other questions about ingestion.

**Comment by frankban** [comment] 2016-05-19 23:03
@bac can we close this bug?

**Closed as completed** 2016-08-25 19:07 UTC
Labels: bug, needs-feedback
