### ISSUE TITLE
Docs: link styles have changed making it hard to see some links

### ISSUE THREAD

**Issue by evilnick** [canonical/jujucharms.com#266] opened 2016-05-12 15:04 UTC
The links throughout docs have changed to an underline from their previous style. In some cases (e.g. links within notes) where small font sizes are used it is now barely possible to tell there is actually a link there at all.

**Comment by evilnick** [comment] 2016-05-12 15:33
Also, it looks pretty silly in the navigation

**Comment by anthonydillon** [comment] 2016-05-20 02:57
@Lucapaulina what you think?

**Comment by urosj** [comment] 2016-08-25 18:32
This has been changed partially due to WCAG compliance AFAIK.

**Comment by spencerbygraves** [comment] 2016-09-21 14:09
Work is ongoing to choose a new link style.

See - https://github.com/CanonicalLtd/juju-design/issues/154

**Comment by pmatulis** [comment] 2016-09-22 16:32
Links in the text body looks fine but the Juju doc menu still looks bad.

**Comment by anthonydillon** [comment] 2016-09-26 15:10
Thanks, the navigation menu links should not have underlines anyway so I will remove them for the mean time. There is a upcoming change to link styling which will resolve this fully.

**Comment by frankban** [comment] 2017-03-03 09:58
@anthonydillon is this fixed? If so, could you please close this bug? Thanks!

**Comment by anthonydillon** [comment] 2017-03-03 11:01
Yes, this is by design: https://github.com/CanonicalLtd/juju-design/issues/154#issuecomment-250495649.

**Closed as completed by anthonydillon** 2017-03-03 11:01 UTC
Labels: design
