### ISSUE TITLE
jujucharms.com/<charm-name> revision history does not match current revision history

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#196] opened 2016-01-11 16:14 UTC
For example the revision history for the juju-gui charm is:
https://jujucharms.com/juju-gui/
by jrwren@xmtp.net 2015-09-18
[r=mhilton,makyo] update nrpe check for non-legacy server 
by Francesco Banconi 2015-08-12
New charm release 1.4.5.

But, Launchpad (source of truth has)
https://code.launchpad.net/~juju-gui-charmers/charms/trusty/juju-gui/trunk
133. By Francesco Banconi on 2015-11-09
New charm release 1.4.6.
1. By Francesco Banconi on 2015-11-09
   New charm release.
2. By Jay R. Wren on 2015-09-18
   [r=mhilton,makyo] update nrpe check for non-legacy server
3. By Francesco Banconi on 2015-08-12
   New charm release 1.4.5.

**Comment by matthewdupre** [comment] 2016-01-11 16:57
I'm seeing the same problem with this charm: https://jujucharms.com/u/project-calico/bird/trusty/ not keeping the history up to date with the code: https://code.launchpad.net/~project-calico/charms/trusty/bird/trunk.  The last 3 revisions are missing from the store, despite two of them being committed back in August.

The actual charm published in the store has picked up the code changes correctly.

**Comment by bac** [comment] 2016-01-11 18:47
This issue is a duplicate of #189. The ingestion process is being investigated.

**Closed as completed by bac** 2016-01-11 18:47 UTC
Labels: duplicate

**Comment by bac** [comment] 2016-01-11 21:03
@arosales Thanks for this issue.  Its worth noting that the new charmstore now allows direct upload of charms, which bypasses Launchpad.  We've moved development of the juju-gut-charm to github and now upload directly so the disconnect you see with that charm is explainable (though still confusing).

As noted on the other issue report, a problem was seen with a stuck process and the process was restarted.  Charms have now been ingested again.

**Comment by bac** [comment] 2016-01-11 21:04
@matthewdupre Your charm appears to be in sync now. Let me know if you see problems again.

**Comment by Yrrsinn** [comment] 2016-01-12 16:41
@bac I'm interested in 'Its worth noting that the new charmstore now allows direct upload of charms, which bypasses Launchpad.' 
Can you provide me a pointer to the corresponding documentation? https://jujucharms.com/docs/devel/authors-charm-store only describes the approach using Launchpad.
